#!/bin/bash

src=~/dotfiles
dest=~/.config

dots=("awesome" "kitty" "zsh" "neofetch" "lf" "sxhkd")

mkdir -p "$dest".old


for file in "${dots[@]}";
do
  echo "Backing up $dest"
  mv "$dest"/"$file" "$dest".old/
  
  echo "linking file $file to $dest";
  ln -sf "$src"/"$file" "$dest"
done


