#!/bin/sh

option=$1
touchpad="SynPS/2 Synaptics TouchPad"

if [ "$option" = "on" ]; then
  xinput set-prop "$touchpad" "Device Enabled" 1
elif [ "$option" = "off" ]; then
  xinput set-prop "$touchpad" "Device Enabled" 0
else
  echo "unsupported argument"
  echo $option
fi

